"""add user settings columns

Revision ID: d07a43142255
Revises: 982344ab063e
Create Date: 2026-06-25 16:08:02.011833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07a43142255'
down_revision = '982344ab063e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calm_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daily_target', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_target')
        batch_op.drop_column('calm_mode')

    # ### end Alembic commands ###
